name: mi

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Action to trigger (login)"
        required: true
        default: "login"

env:
  AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
  AZOPS_STATE: "azops"
  AZOPS_DEFAULT_DEPLOYMENT_REGION: "northeurope"
  AZOPS_ENROLLMENT_ACCOUNT: ""
  AZOPS_OFFER_TYPE: "MS-AZR-0017P"
  AZOPS_IGNORE_CONTEXT_CHECK: "0"
  AZOPS_INVALIDATE_CACHE: "1"
  AZOPS_SKIP_RESOURCE_GROUP: "1"
  AZOPS_SKIP_POLICY: "0"
  AZOPS_THROTTLE_LIMIT: "10"
  AZOPS_SUPPORT_PARTIAL_MG_DISCOVERY: 0
  GITHUB_USERNAME: "AzOps"
  GITHUB_EMAIL: "noreply@azure.com"
  GITHUB_PULL_REQUEST: "Azure Change Notification"
  GITHUB_CONTEXT: ${{ toJson(github) }}
  GITHUB_ISSUE: ${{ github.event.pull_request._links.issue.href }}
  GITHUB_COMMENTS: ${{ github.event.pull_request._links.comments.href }}
  GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}
  GITHUB_HEAD_REF: ${{ github.event.pull_request.head.ref }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  SCM_PLATFORM: "GitHub"
  VERBOSE: "0"
  DEBUG: "0"

jobs:
  login:
    timeout-minutes: 120
    name: Login
    runs-on: self-hosted
    #runs-on: ubuntu-latest
    steps:
      - name: Actions checkout
        uses: actions/checkout@v2
      - name: GitHub context
        run: echo "$GITHUB_CONTEXT"
      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}
      - name: Run Az CLI script
        run: |
          az webapp list --query "[?state=='Running']"
